name: thefourthmachine
favicon: null
layout_spectrum: 0.88106
typography_spectrum: 0.658158193808049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e28b3a'
    - '#2b3843'
    - '#b4763c'
    - '#1e272f'
    - '#ff5500'
  brandStrength: 0
  lightness: 0.13340656412765384
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
